import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TrendingUp, Sparkles } from 'lucide-react';
export function CapacityIntelligenceModule() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-2xl font-extrabold text-slate-900 tracking-tight flex items-center gap-3", children: [_jsx(TrendingUp, { className: "text-blue-600" }), "National Resource Planning & Capacity Intelligence"] }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: "AI-Driven Deployment Recommendations \u2022 Infrastructure Gap Identification & OPD Peak Load Forecasting" })] }), _jsx("span", { className: "px-3 py-1 bg-blue-50 text-blue-700 border border-blue-200 rounded-xl text-xs font-bold font-mono animate-fade-in", children: "AI Optimization Engine: ACTIVE" })] }), _jsx("div", { className: "grid grid-cols-3 gap-4", children: [
                    { state: 'Maharashtra', facilities: 18, kiosks: 410, intake: '6,120/day', utilization: 82, rec: 'Deploy +35 kiosks to high-load districts' },
                    { state: 'Uttar Pradesh', facilities: 24, kiosks: 320, intake: '5,100/day', utilization: 89, rec: 'Deploy +45 kiosks to tier-2 civil hospitals' },
                    { state: 'Tamil Nadu', facilities: 16, kiosks: 290, intake: '4,200/day', utilization: 74, rec: 'Optimal capacity distribution' },
                ].map((st, idx) => (_jsxs("div", { className: "p-5 bg-white border border-slate-200 rounded-2xl shadow-sm space-y-3 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md animate-slide-up stagger-item", style: { animationDelay: `${idx * 40}ms` }, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "font-extrabold text-slate-900 text-base", children: st.state }), _jsxs("span", { className: "text-xs font-mono font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-200", children: [st.utilization, "% Avg Load"] })] }), _jsxs("div", { className: "grid grid-cols-3 gap-2 text-[11px] text-slate-500 font-mono", children: [_jsxs("div", { children: ["Facilities: ", _jsx("span", { className: "text-slate-900 font-bold", children: st.facilities })] }), _jsxs("div", { children: ["Kiosks: ", _jsx("span", { className: "text-slate-900 font-bold", children: st.kiosks })] }), _jsxs("div", { children: ["Daily: ", _jsx("span", { className: "text-blue-600 font-bold", children: st.intake })] })] }), _jsxs("div", { className: "p-3 bg-indigo-50 border border-indigo-200 rounded-xl text-xs text-indigo-700 flex items-start gap-2", children: [_jsx(Sparkles, { size: 16, className: "shrink-0 mt-0.5 text-indigo-600" }), _jsxs("div", { children: [_jsx("span", { className: "font-bold block text-[11px]", children: "NHA Recommendation" }), _jsx("span", { children: st.rec })] })] })] }, idx))) })] }));
}
//# sourceMappingURL=CapacityIntelligenceModule.js.map