import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Users, Settings } from 'lucide-react';
export function RbacPoliciesModule() {
    const [sessionTimeout, setSessionTimeout] = useState(120);
    const [kioskTimeout, setKioskTimeout] = useState(45);
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-2xl font-extrabold text-slate-900 tracking-tight flex items-center gap-3", children: [_jsx(Users, { className: "text-blue-600" }), "Roles, Authority & Jurisdiction Governance (RBAC)"] }), _jsx("p", { className: "text-xs text-slate-500 mt-1", children: "Jurisdiction Scoping \u2022 `National` \u2192 `State` \u2192 `District` \u2192 `Facility` \u2192 `Doctor` \u2192 `Kiosk`" })] }), _jsx("span", { className: "px-3 py-1 bg-blue-50 text-blue-700 border border-blue-200 rounded-xl text-xs font-bold font-mono", children: "Jurisdiction Scoping Enforced" })] }), _jsxs("div", { className: "bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4 animate-slide-up", children: [_jsx("h3", { className: "text-sm font-bold text-slate-900", children: "National Authority RBAC Hierarchy" }), _jsx("div", { className: "grid grid-cols-6 gap-3 text-xs", children: [
                            { role: 'National Authority', scope: 'All 36 States & UTs', access: 'Infrastructure, Policy, AI Governance, ABDM' },
                            { role: 'State Authority', scope: 'Single State Jurisdiction', access: 'State Facilities, Deployment, Performance' },
                            { role: 'District Authority', scope: 'Single District Scope', access: 'District Hospitals, Incidents, Capacity' },
                            { role: 'Hospital Admin', scope: 'Facility Scope', access: 'Staff, Kiosks, RFID Inventory, OPD Config' },
                            { role: 'Doctor / Clinician', scope: 'Assigned Patient Scope', access: 'Patient Intake, AI Summary, Consultation' },
                            { role: 'Kiosk Terminal', scope: 'Local Session Scope', access: 'Intake Interface, RFID UID Tap, OCR' },
                        ].map((r, idx) => (_jsxs("div", { className: "p-3 bg-slate-100 border border-slate-200 rounded-xl space-y-2 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md animate-slide-up stagger-item", style: { animationDelay: `${60 + idx * 40}ms` }, children: [_jsx("span", { className: "font-bold text-blue-700 block text-[11px]", children: r.role }), _jsxs("span", { className: "text-[10px] text-slate-500 block font-mono", children: ["Scope: ", r.scope] }), _jsx("span", { className: "text-[10px] text-slate-600 block leading-tight", children: r.access })] }, idx))) })] }), _jsxs("div", { className: "bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4 animate-slide-up stagger-item", style: { animationDelay: '320ms' }, children: [_jsxs("h3", { className: "text-sm font-bold text-slate-900 flex items-center gap-2", children: [_jsx(Settings, { size: 16, className: "text-blue-600" }), "National System Defaults & Policy Configuration"] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 text-xs", children: [_jsxs("div", { className: "p-4 bg-slate-100 border border-slate-200 rounded-xl space-y-2", children: [_jsx("span", { className: "font-bold text-slate-700 block", children: "Kiosk Inactivity Timeout (Seconds)" }), _jsx("input", { type: "number", value: kioskTimeout, onChange: (e) => setKioskTimeout(Number(e.target.value)), className: "w-full bg-white border border-slate-300 rounded-lg px-3 py-2 text-xs font-mono text-slate-900 transition-colors focus:outline-none focus:border-blue-400" }), _jsx("span", { className: "text-[10px] text-slate-500 block", children: "Automatically resets kiosk intake screen to initial tap prompt." })] }), _jsxs("div", { className: "p-4 bg-slate-100 border border-slate-200 rounded-xl space-y-2", children: [_jsx("span", { className: "font-bold text-slate-700 block", children: "Doctor Consultation Session Timeout (Minutes)" }), _jsx("input", { type: "number", value: sessionTimeout, onChange: (e) => setSessionTimeout(Number(e.target.value)), className: "w-full bg-white border border-slate-300 rounded-lg px-3 py-2 text-xs font-mono text-slate-900 transition-colors focus:outline-none focus:border-blue-400" }), _jsx("span", { className: "text-[10px] text-slate-500 block", children: "Maximum doctor session idle threshold before requiring re-auth." })] })] })] })] }));
}
//# sourceMappingURL=RbacPoliciesModule.js.map